<?php if($block->getDataHelper()->isIysSmsEnabled() || $block->getDataHelper()->isIysCallEnabled()):?>
    <fieldset class="fieldset info">
        <div class="field required">
            <label for="telephone" class="label"><span><?= __('Telephone') ?></span></label>
            <div class="control">
                <input type="text" name="telephone" id="telephone" value="<?php echo $block->getTelephone() ?>" title="<?php echo __('Telephone') ?>" class="input-text" data-validate="{required:true, 'validate-phoneStrict':true}">
            </div>
        </div>
    </fieldset>
<?php endif; ?>
